### ISSUE TITLE
OcrdExif: PNG has no tag for dpi unit!

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#395]
When I open a PNG image file which includes DPI meta-data, (which is supported since 2014 by Pillow but still undocumented), core currently gives me:
```
  File "ocrd_modelfactory/__init__.py", line 77, in page_from_file
    return page_from_image(input_file)
  File "ocrd_modelfactory/__init__.py", line 49, in page_from_image
    exif = exif_from_filename(input_file.local_filename)
  File "ocrd_modelfactory/__init__.py", line 33, in exif_from_filename
    ocrd_exif = OcrdExif(pil_img)
  File "ocrd_models/ocrd_exif.py", line 42, in __init__
    self.resolutionUnit = 'cm' if img.tag.get(296) == 3 else 'inches'
AttributeError: 'PngImageFile' object has no attribute 'tag'
```

And that's exactly right: That tag is only valid for JPEG. Pillow's PNG plugin converts the fixed implicit _meter_ unit to a fixed implicit _inch_ [here](https://github.com/python-pillow/Pillow/blob/ef4a0b2f4c9346db37140f102e80068abc280167/src/PIL/PngImagePlugin.py#L430).

**Comment by bertsky** [comment]
Or do you want me to make a PR myself?

**Comment by bertsky** [comment]
(It's a regression from 75ef3811.)

**Comment by kba** [comment]
I'll fix it.
