### ISSUE TITLE
bagger spill regression from 1f0ce7dc

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#314]
Our `ocrd zip spill` is currently broken: it now has an option `dest` (no more `directory`) but the function has no parameter of that name. So click will always give you:

```TypeError: spill() got an unexpected keyword argument 'dest'```
